<a href="https://colab.research.google.com/github/yasmeen0404/numpy_fundamentals/blob/main/numpy_basics_ou_examples_indexing_slicing_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(4,)

In [ ]:
a.size

4

In [ ]:
b = np.array([(1,2,3,4),(4,5,6,7)])

In [ ]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
b.shape

(2, 4)

In [ ]:
b.size

8

In [ ]:
a.sum()

10

In [ ]:
a.prod()

24

In [ ]:
a.min()

1

In [ ]:
a.max()

4

In [ ]:
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
b= b.reshape(4,2)

In [ ]:
print(b)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
b.shape

(4, 2)

In [ ]:
 b[0,1]

2

In [ ]:
b[1,1]

4

In [ ]:
b[0,0]

1

In [ ]:
b[0,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [ ]:
c= np.array([(1,2,3,4),(4,5,6,7)])
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
c.sum(axis=0)

array([ 5,  7,  9, 11])

In [ ]:
c.sum(axis=1)

array([10, 22])

In [ ]:
import pandas as pd
df=pd.DataFrame({'col1':['A','B','B','A'],'col2':[1,2,2,3]})

In [ ]:
df

col1  col2
0    A     1
1    B     2
2    B     2
3    A     3

In [ ]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
df[df.duplicated()]

col1  col2
2    B     2

In [ ]:
df1 = df.drop_duplicates()

In [ ]:
df1

col1  col2
0    A     1
1    B     2
3    A     3

In [ ]:
df2=df1.reset_index()

In [ ]:
df2

index col1  col2
0      0    A     1
1      1    B     2
2      3    A     3

In [ ]:
df3=df2.drop('index',axis=1)

In [ ]:
df3

col1  col2
0    A     1
1    B     2
2    A     3

In [ ]:
# prompt: NumPy Arrays Creation Using array() Function

import numpy as np

# Create a 1-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Create a 2-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Create a 3-dimensional array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# prompt: array attribute examples, more examples

# Accessing elements using indexing
print("First element of arr1:", arr1[0])
print("Element at row 1, column 2 of arr2:", arr2[1, 2])
print("Element at depth 0, row 1, column 0 of arr3:", arr3[0, 1, 0])

# Array data type
print("Data type of arr1:", arr1.dtype)

# Array dimensions
print("Number of dimensions of arr2:", arr2.ndim)

# Array shape (number of elements along each axis)
print("Shape of arr3:", arr3.shape)

# Array size (total number of elements)
print("Size of arr1:", arr1.size)

# Reshaping arrays
arr4 = arr1.reshape(1, 5)  # Reshape to a 2D array with 1 row and 5 columns
print("Reshaped arr1:\n", arr4)

# Transposing arrays
arr5 = arr2.transpose()  # Swap rows and columns
print("Transposed arr2:\n", arr5)

# Array concatenation
arr6 = np.concatenate((arr1, np.array([6, 7, 8])))  # Concatenate two arrays along the existing axis
print("Concatenated arr1:\n", arr6)

# Array splitting
arr7 = np.array_split(arr1, 4)  # Split array into 3 equal parts
print("Split arr1:\n", arr7)

# Array sorting
arr8 = np.array([5, 2, 8, 1, 9])
arr8.sort()  # Sort array in ascending order
print("Sorted arr8:\n", arr8)



First element of arr1: 1
Element at row 1, column 2 of arr2: 6
Element at depth 0, row 1, column 0 of arr3: 3
Data type of arr1: int64
Number of dimensions of arr2: 2
Shape of arr3: (2, 2, 2)
Size of arr1: 5
Reshaped arr1:
 [[1 2 3 4 5]]
Transposed arr2:
 [[1 4]
 [2 5]
 [3 6]]
Concatenated arr1:
 [1 2 3 4 5 6 7 8]
Split arr1:
 [array([1, 2]), array([3]), array([4]), array([5])]
Sorted arr8:
 [1 2 5 8 9]


In [ ]:
# prompt: array attributes

import numpy as np
import pandas as pd

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Array attributes
print("Array:", arr)
print("Data type:", arr.dtype)  # Data type of the array elements
print("Number of dimensions:", arr.ndim)  # Number of dimensions (e.g., 1 for a vector, 2 for a matrix)
print("Shape:", arr.shape)  # Dimensions of the array as a tuple (e.g., (5,) for a 1D array with 5 elements)
print("Size:", arr.size)  # Total number of elements in the array
print("Item size:", arr.itemsize)  # Size in bytes of each element
print("Data:", arr.data)  # Buffer containing the array's elements


# Other useful attributes and methods
print("Mean:", arr.mean())  # Calculate the mean of the array
print("Standard deviation:", arr.std())  # Calculate the standard deviation
print("Minimum:", arr.min())  # Find the minimum value
print("Maximum:", arr.max())  # Find the maximum value
print("Sum:", arr.sum())
print("variance:", arr.var()) # Calculate the variance

Array: [1 2 3 4 5]
Data type: int64
Number of dimensions: 1
Shape: (5,)
Size: 5
Item size: 8
Data: <memory at 0x7a379af91300>
Mean: 3.0
Standard deviation: 1.4142135623730951
Minimum: 1
Maximum: 5
Sum: 15
variance: 2.0


In [ ]:
# prompt: integer indexing , array indexing

# Integer indexing
print("Element at index 2:", arr[2])  # Access the element at index 2 (which is the third element)

# Array indexing (slicing)
print("Elements from index 1 to 3:", arr[1:4])  # Access elements from index 1 to 3 (exclusive)
print("Every other element:", arr[::2])  # Access every other element
print("Reverse the array:", arr[::-1])  # Reverse the array

# Boolean indexing
bool_arr = arr > 2  # Create a boolean array where True indicates elements greater than 2
print("Boolean array:", bool_arr)
print("Elements greater than 2:", arr[bool_arr])  # Filter the original array based on the boolean array

# Fancy indexing
indices = [0, 2, 4]  # List of indices to select
print("Elements at specified indices:", arr[indices])   # Select elements at the specified indices

Element at index 2: 3
Elements from index 1 to 3: [2 3 4]
Every other element: [1 3 5]
Reverse the array: [5 4 3 2 1]
Boolean array: [False False  True  True  True]
Elements greater than 2: [3 4 5]
Elements at specified indices: [1 3 5]


In [ ]:
# prompt: integer indexing, array indexing more examples

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr2d)

# Integer indexing for selecting specific elements
print("Element at row 1, column 2:", arr2d[1, 2])  # Access the element at row 1, column 2 (which is 6)
print("Element at row 0, column 0:", arr2d[0, 0])  # Access the element at row 0, column 0 (which is 1)

# Array slicing to select a portion of the array
print("First two rows and all columns:\n", arr2d[:2, :])  # Select the first two rows and all columns
print("Last row and all columns:\n", arr2d[-1, :])  # Select the last row and all columns
print("All rows and the first two columns:\n", arr2d[:, :2])  # Select all rows and the first two columns

# Using steps in slicing
print("Every other row and every other column:\n", arr2d[::2, ::2])  # Select every other row and every other column

# Boolean indexing to filter elements based on a condition
print("Elements greater than 5:\n", arr2d[arr2d > 5])  # Select elements greater than 5

# Fancy indexing with a list of indices
row_indices = [0, 2]  # Select rows 0 and 2
col_indices = [1, 2]  # Select columns 1 and 2
print("Elements at specified row and column indices:\n", arr2d[row_indices, col_indices])  # Select elements at (0,1), (2,2)


# Example: Selecting elements based on a condition and then performing an operation on them
# Select elements in the array that are greater than 5 and double them
filtered_elements = arr2d[arr2d > 5] * 2
print("Elements greater than 5, doubled:\n", filtered_elements)



2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
Element at row 0, column 0: 1
First two rows and all columns:
 [[1 2 3]
 [4 5 6]]
Last row and all columns:
 [7 8 9]
All rows and the first two columns:
 [[1 2]
 [4 5]
 [7 8]]
Every other row and every other column:
 [[1 3]
 [7 9]]
Elements greater than 5:
 [6 7 8 9]
Elements at specified row and column indices:
 [2 9]
Elements greater than 5, doubled:
 [12 14 16 18]


In [ ]:
# prompt: boolean array indexing examples , 10 examples

import numpy as np

# Example 1: Selecting elements greater than 5
arr = np.array([1, 6, 3, 8, 2, 9])
bool_arr = arr > 5
print(arr[bool_arr])  # Output: [6 8 9]

# Example 2: Selecting even numbers
arr = np.array([1, 2, 3, 4, 5, 6])
bool_arr = arr % 2 == 0
print(arr[bool_arr])  # Output: [2 4 6]

# Example 3: Selecting elements between 3 and 7
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
bool_arr = (arr > 3) & (arr < 7)
print(arr[bool_arr])  # Output: [4 5 6]

# Example 4: Selecting elements not equal to 5
arr = np.array([1, 2, 5, 4, 5, 6])
bool_arr = arr != 5
print(arr[bool_arr])  # Output: [1 2 4 6]

# Example 5: Selecting elements in a 2D array based on a condition in one column
arr = np.array([[1, 2], [3, 4], [5, 6]])
bool_arr = arr[:, 0] > 3
print(arr[bool_arr])  # Output: [[5 6]]

# Example 6: Selecting elements based on multiple conditions
arr = np.array([1, 2, 3, 4, 5, 6])
bool_arr = (arr > 2) & (arr < 5)
print(arr[bool_arr])  # Output: [3 4]

# Example 7: Inverting a boolean condition
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr < 3
print(arr[~bool_arr])  # Output: [3 4 5]

# Example 8: Combining boolean indexing with other operations
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2
print(arr[bool_arr] * 2)  # Output: [6 8 10]

# Example 9: Selecting rows based on a condition in a DataFrame
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
bool_arr = df['A'] > 1
print(df[bool_arr])

# Example 10: Selecting elements from a 2D array based on a condition in each row
arr = np.array([[1, 2], [3, 4], [5, 6]])
bool_arr = arr > 1
print(arr[bool_arr])

[6 8 9]
[2 4 6]
[4 5 6]
[1 2 4 6]
[[5 6]]
[3 4]
[3 4 5]
[ 6  8 10]
   A  B
1  2  5
2  3  6
[2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
bool_arr = arr[:, 0] > 3
print(arr[bool_arr])

[[5 6]]


In [ ]:
bool_arr = arr[:, 0] > 3

In [ ]:
bool_arr

array([False, False,  True])

In [ ]:
arr.shape

(3, 2)

In [ ]:
print(arr[bool_arr])

[[5 6]]


In [ ]:
# prompt: boolean indexing new examples, give 5 , think differently

# Example 1: Selecting rows in a DataFrame where a specific column contains a substring
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                   'Age': [25, 30, 22, 28],
                   'City': ['New York', 'London', 'Paris', 'Tokyo']})
bool_arr = df['City'].str.contains('on')
print(df[bool_arr])


# Example 2: Selecting rows in a DataFrame where a specific column value is within a range
df = pd.DataFrame({'Product': ['A', 'B', 'C', 'D'],
                   'Price': [10, 25, 15, 30],
                   'Quantity': [5, 2, 8, 3]})
bool_arr = df['Price'].between(10, 20)
print(df[bool_arr])


# Example 3: Selecting rows in a DataFrame where multiple conditions are met based on column values
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                   'Age': [25, 30, 22, 28],
                   'City': ['New York', 'London', 'Paris', 'Tokyo']})
bool_arr = (df['Age'] > 25) & (df['City'].str.startswith('L'))
print(df[bool_arr])


# Example 4: Selecting rows in a DataFrame where a specific column value is in a list of values
df = pd.DataFrame({'Fruit': ['Apple', 'Banana', 'Orange', 'Grape'],
                   'Color': ['Red', 'Yellow', 'Orange', 'Purple'],
                   'Price': [1, 0.5, 0.75, 1.25]})
bool_arr = df['Fruit'].isin(['Apple', 'Orange'])
print(df[bool_arr])


# Example 5: Selecting rows in a DataFrame where a specific column value is null or not null
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                   'Age': [25, None, 22, 28],
                   'City': ['New York', 'London', 'Paris', 'Tokyo']})
bool_arr = df['Age'].notnull()
print(df[bool_arr])

  Name  Age    City
1  Bob   30  London
  Product  Price  Quantity
0       A     10         5
2       C     15         8
  Name  Age    City
1  Bob   30  London
    Fruit   Color  Price
0   Apple     Red   1.00
2  Orange  Orange   0.75
      Name   Age      City
0    Alice  25.0  New York
2  Charlie  22.0     Paris
3    David  28.0     Tokyo


In [ ]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
bool_arr = df['A'] > 1
print(df[bool_arr])
bool_arr

   A  B
1  2  5
2  3  6


0    False
1     True
2     True
Name: A, dtype: bool

In [ ]:
# prompt: slicing and iterating in arrays , give 10 examples

# Example 1: Slicing a 1D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # Output: [2 3 4]

# Example 2: Iterating through a 1D array
for element in arr:
  print(element)

# Example 3: Slicing a 2D array (rows and columns)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

# Example 4: Iterating through a 2D array (row-wise)
for row in arr2d:
  print(row)

# Example 5: Iterating through a 2D array (element-wise)
for row in arr2d:
  for element in row:
    print(element)

# Example 6: Selecting elements based on a condition (boolean indexing)
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2
print(arr[bool_arr])  # Output: [3 4 5]

# Example 7: Iterating through a boolean array
for i in bool_arr:
  print(i)

# Example 8: Selecting elements using fancy indexing
arr = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]
print(arr[indices])  # Output: [1 3 5]

# Example 9: Iterating through a list of indices
for index in indices:
  print(arr[index])

# Example 10: Using slicing with steps
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1:9:2])  # Output: [2 4 6 8]

[2 3 4]
1
2
3
4
5
[[2 3]
 [5 6]]
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
[3 4 5]
False
False
True
True
True
[1 3 5]
1
3
5
[2 4 6 8]


In [ ]:
# prompt: slicing and iterating some more 5 examples, think differently

# Example 1: Slicing a NumPy array with a step
import pandas as pd
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1:8:2])  # Output: [2 4 6] (start at index 1, end at index 8, step by 2)


# Example 2: Iterating through a DataFrame using iterrows()
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 22]})
for index, row in df.iterrows():
  print(f"Index: {index}, Name: {row['Name']}, Age: {row['Age']}")


# Example 3: Slicing a Pandas DataFrame using loc with boolean indexing
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 22]})
print(df.loc[df['Age'] > 25, ['Name']]) # Selects the 'Name' column for rows where Age is greater than 25


# Example 4: Iterating through a Pandas DataFrame using itertuples()
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 22]})
for row in df.itertuples():
  print(f"Index: {row.Index}, Name: {row.Name}, Age: {row.Age}")


# Example 5: Slicing a NumPy array with negative indices
arr = np.array([1, 2, 3, 4, 5])
print(arr[-3:])  # Output: [3 4 5] (select the last 3 elements)

[2 4 6 8]
Index: 0, Name: Alice, Age: 25
Index: 1, Name: Bob, Age: 30
Index: 2, Name: Charlie, Age: 22
  Name
1  Bob
Index: 0, Name: Alice, Age: 25
Index: 1, Name: Bob, Age: 30
Index: 2, Name: Charlie, Age: 22
[3 4 5]


In [ ]:
# prompt: basic artithematic operations in numpy, give 10 examples

# Example 1: Addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print("Addition:", result)

# Example 2: Subtraction
result = arr2 - arr1
print("Subtraction:", result)

# Example 3: Multiplication
result = arr1 * arr2
print("Multiplication:", result)

# Example 4: Division
result = arr2 / arr1
print("Division:", result)

# Example 5: Element-wise square root
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print("Square root:", result)

# Example 6: Element-wise exponentiation
result = np.exp(arr)
print("Exponentiation:", result)

# Example 7: Dot product of two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.dot(arr1, arr2)
print("Dot product:", result)

# Example 8: Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.matmul(matrix1, matrix2)
print("Matrix multiplication:\n", result)

# Example 9: Element-wise modulo operation
arr1 = np.array([5, 10, 15])
arr2 = np.array([2, 3, 4])
result = np.mod(arr1, arr2)
print("Modulo:", result)


# Example 10: Element-wise floor division
arr1 = np.array([10, 15, 20])
arr2 = np.array([3, 4, 5])
result = np.floor_divide(arr1, arr2)
print("Floor division:", result)

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Square root: [2. 3. 4.]
Exponentiation: [5.45981500e+01 8.10308393e+03 8.88611052e+06]
Dot product: 32
Matrix multiplication:
 [[19 22]
 [43 50]]
Modulo: [1 1 3]
Floor division: [3 3 4]


In [ ]:
# prompt: more examples for aritematoc operatiosn , think differently

# Example 1: Calculating the sum of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
sum_of_elements = np.sum(arr)
print("Sum of elements:", sum_of_elements)

# Example 2: Calculating the product of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
product_of_elements = np.prod(arr)
print("Product of elements:", product_of_elements)

# Example 3: Calculating the mean of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
mean_of_elements = np.mean(arr)
print("Mean of elements:", mean_of_elements)

# Example 4: Calculating the standard deviation of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
std_dev_of_elements = np.std(arr)
print("Standard deviation of elements:", std_dev_of_elements)

# Example 5: Calculating the variance of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
variance_of_elements = np.var(arr)
print("Variance of elements:", variance_of_elements)

# Example 6: Calculating the cumulative sum of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
cumulative_sum_of_elements = np.cumsum(arr)
print("Cumulative sum of elements:", cumulative_sum_of_elements)

# Example 7: Calculating the cumulative product of elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
cumulative_product_of_elements = np.cumprod(arr)
print("Cumulative product of elements:", cumulative_product_of_elements)

# Example 8: Calculating the difference between consecutive elements in a NumPy array
arr = np.array([1, 2, 3, 4, 5])
difference_between_consecutive_elements = np.diff(arr)
print("Difference between consecutive elements:", difference_between_consecutive_elements)

# Example 9: Calculating the element-wise maximum between two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 1, 6])
element_wise_maximum = np.maximum(arr1, arr2)
print("Element-wise maximum:", element_wise_maximum)

# Example 10: Calculating the element-wise minimum between two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 1, 6])
element_wise_minimum = np.minimum(arr1, arr2)
print("Element-wise minimum:", element_wise_minimum)


Sum of elements: 15
Product of elements: 120
Mean of elements: 3.0
Standard deviation of elements: 1.4142135623730951
Variance of elements: 2.0
Cumulative sum of elements: [ 1  3  6 10 15]
Cumulative product of elements: [  1   2   6  24 120]
Difference between consecutive elements: [1 1 1 1]
Element-wise maximum: [4 2 6]
Element-wise minimum: [1 1 3]
